#!/usr/bin/env bash
# Shared paths, logging, and configuration for the AID-HS CLI.

set -euo pipefail

# Resolve pipeline root (parent of lib/)
if [[ -z "${AID_ROOT:-}" ]]; then
  AID_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
export AID_ROOT

AID_STATE_DIR="${AID_ROOT}/.aid"
AID_LOG_DIR="${AID_ROOT}/logs"
AID_CONFIG="${AID_STATE_DIR}/config.env"
AID_PID_FILE="${AID_STATE_DIR}/run.pid"
AID_INSTALL_LOG="${AID_LOG_DIR}/install.log"
: "${AID_RUN_LOG:=${AID_LOG_DIR}/run.log}"
: "${AID_EXTRA_BINDS:=}"
AID_LICENSE_FILE="${AID_ROOT}/aidhs_license.txt"
AID_DATA_DIR="${AID_ROOT}"
AID_SIF="${AID_STATE_DIR}/aidhs.sif"
AID_IMAGE="meldproject/aidhs:latest"
AID_PIPELINE_SCRIPT="scripts/new_patient_pipeline/new_patient_pipeline.py"
AID_PREPARE_SCRIPT="scripts/new_patient_pipeline/prepare_aidhs.py"

mkdir -p "${AID_STATE_DIR}" "${AID_LOG_DIR}" "${AID_ROOT}/input" "${AID_ROOT}/output"

# HPC nodes often mount /tmp with noexec — use pipeline-local dirs by default
setup_apptainer_paths() {
  local cache="${AID_STATE_DIR}/cache"
  local tmp="${AID_STATE_DIR}/tmp"
  mkdir -p "${cache}" "${tmp}"
  if [[ -z "${APPTAINER_CACHEDIR:-}" && -z "${SINGULARITY_CACHEDIR:-}" ]]; then
    export APPTAINER_CACHEDIR="${cache}"
    export SINGULARITY_CACHEDIR="${cache}"
  fi
  if [[ -z "${APPTAINER_TMPDIR:-}" && -z "${SINGULARITY_TMPDIR:-}" ]]; then
    export APPTAINER_TMPDIR="${tmp}"
    export SINGULARITY_TMPDIR="${tmp}"
  fi
}

log() {
  local level="$1"
  shift
  local ts
  ts="$(date '+%Y-%m-%d %H:%M:%S')"
  echo "[${ts}] [${level}] $*" | tee -a "${AID_LOG_FILE:-/dev/null}" 2>/dev/null || echo "[${ts}] [${level}] $*"
}

die() {
  log ERROR "$@"
  exit 1
}

load_config() {
  if [[ -f "${AID_CONFIG}" ]]; then
    # shellcheck source=/dev/null
    source "${AID_CONFIG}"
  fi
  : "${AID_RUNTIME:=auto}"
  : "${AID_USE_GPU:=auto}"
  : "${AID_DATA_DIR:=${AID_ROOT}}"
  : "${AID_LICENSE_FILE:=${AID_ROOT}/aidhs_license.txt}"
  : "${AID_SIF:=${AID_STATE_DIR}/aidhs.sif}"
  : "${AID_IMAGE:=meldproject/aidhs:latest}"
  : "${AID_EXTRA_BINDS:=}"
}

save_config() {
  mkdir -p "${AID_STATE_DIR}"
  cat >"${AID_CONFIG}" <<EOF
# AID-HS pipeline configuration (generated by ./aid install)
AID_ROOT='${AID_ROOT}'
AID_RUNTIME='${AID_RUNTIME}'
AID_USE_GPU='${AID_USE_GPU}'
AID_DATA_DIR='${AID_DATA_DIR}'
AID_LICENSE_FILE='${AID_LICENSE_FILE}'
AID_SIF='${AID_SIF}'
AID_IMAGE='${AID_IMAGE}'
EOF
}

require_license() {
  if [[ ! -f "${AID_LICENSE_FILE}" ]]; then
    die "License not found: ${AID_LICENSE_FILE}
Register at: https://docs.google.com/forms/d/e/1FAIpQLSdPbtraBZ2s0HD1W8qtF11wr_fYVTWZjraED03Rtl2ZjxeRMA/viewform"
  fi
}

is_running() {
  [[ -f "${AID_PID_FILE}" ]] || return 1
  local pid
  pid="$(cat "${AID_PID_FILE}" 2>/dev/null)" || return 1
  [[ -n "${pid}" ]] && kill -0 "${pid}" 2>/dev/null
}

ensure_not_running() {
  if is_running; then
    die "Pipeline is already running (PID $(cat "${AID_PID_FILE}")). Use: ./aid stop"
  fi
}

ensure_installed() {
  load_config
  if [[ ! -f "${AID_CONFIG}" ]]; then
    die "Not installed. Run: ./aid install"
  fi
  if [[ "${AID_RUNTIME}" == "singularity" || "${AID_RUNTIME}" == "apptainer" ]]; then
    [[ -f "${AID_SIF}" ]] || die "Singularity image missing: ${AID_SIF}. Run: ./aid install"
  fi
}

have_cmd() {
  command -v "$1" &>/dev/null
}

detect_runtime() {
  local forced="${1:-auto}"
  if [[ "${forced}" != "auto" ]]; then
    echo "${forced}"
    return
  fi
  if have_cmd apptainer; then
    echo "apptainer"
    return
  fi
  if have_cmd singularity; then
    echo "singularity"
    return
  fi
  if have_cmd docker && docker info &>/dev/null 2>&1; then
    echo "docker"
    return
  fi
  if have_cmd docker; then
    echo "docker"
    return
  fi
  die "No container runtime found. Install Docker or Singularity/Apptainer, or set AID_RUNTIME=docker|singularity|apptainer"
}

singularity_cmd() {
  load_config
  case "${AID_RUNTIME}" in
    apptainer) echo "apptainer" ;;
    singularity) echo "singularity" ;;
    *)
      if have_cmd apptainer; then
        echo "apptainer"
      else
        echo "singularity"
      fi
      ;;
  esac
}

detect_gpu() {
  local mode="${1:-auto}"
  if [[ "${mode}" == "no" || "${mode}" == "false" || "${mode}" == "0" ]]; then
    return 1
  fi
  if [[ "${mode}" == "yes" || "${mode}" == "true" || "${mode}" == "1" ]]; then
    return 0
  fi
  if have_cmd nvidia-smi && nvidia-smi &>/dev/null; then
    return 0
  fi
  return 1
}

gpu_compose_block() {
  if detect_gpu "${AID_USE_GPU}"; then
    cat <<'EOF'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
EOF
  fi
}

setup_bids_defaults() {
  local bids_cfg="${AID_ROOT}/input/bids_config.json"
  local ds_desc="${AID_ROOT}/input/dataset_description.json"
  if [[ ! -f "${bids_cfg}" && -f "${AID_ROOT}/input/bids_config.json.example" ]]; then
    cp "${AID_ROOT}/input/bids_config.json.example" "${bids_cfg}"
    log INFO "Created ${bids_cfg} from example"
  fi
  if [[ ! -f "${ds_desc}" && -f "${AID_ROOT}/input/dataset_description.json.example" ]]; then
    cp "${AID_ROOT}/input/dataset_description.json.example" "${ds_desc}"
    log INFO "Created ${ds_desc} from example"
  fi
}

resolve_demographics_path() {
  local demos="$1"
  if [[ -f "${AID_ROOT}/${demos}" ]]; then
    echo "${demos}"
    return
  fi
  if [[ -f "${AID_ROOT}/input/${demos}" ]]; then
    echo "input/${demos}"
    return
  fi
  die "Demographics file not found: ${demos} (looked in ${AID_ROOT}/ and ${AID_ROOT}/input/)"
}
